### ISSUE TITLE
Runs unlimited

### ISSUE THREAD

**Issue by flatronic** [Hedrauta/Wreckfest-eventloop-randomizer#2]
Hey there, i tried the script and it ends in a never ending "red" error messages ... I did the test with the small racing.txt.

Result in the eventloop looks like: el_add=639846445
el_gamemode=racing
el_laps=0
el_add=gravel1_main_loop
el_gamemode=racing
el_laps=6
el_add=mixed3_short_loop_rev
el_gamemode=racing
el_laps=6
el_add=mixed4_main_circuit
el_gamemode=racing
el_laps=6
el_add=sandpit1_short_loop
el_gamemode=racing
el_laps=6
el_add=mixed7_r1_rev
el_gamemode=racing
el_laps=6
el_add=gravel1_main_loop_rev
el_gamemode=racing
el_laps=6
el_add=mixed3_short_loop
el_gamemode=racing
el_laps=6
el_add=tarmac1_short_circuit_rev
el_gamemode=racing
el_laps=6
el_add=sandpit1_short_loop_rev
el_gamemode=racing
el_laps=6
el_add=tarmac1_short_circuit
el_gamemode=racing
el_laps=6
el_add=mixed4_main_circuit_rev
el_gamemode=racing
el_laps=6
el_add=mixed8_r1
el_gamemode=racing
el_laps=6
el_add=mixed8_r1
el_gamemode=racing
el_laps=6
el_add=mixed8_r1
el_gamemode=racing
el_laps=6

and then midex8 over and over and over ...

As my powershell is German here is the error:
Get-Random : Der Wert "mixed3_short_loop_rev" kann nicht in den Typ "System.Int32" konvertiert werden. Fehler: "Die
Eingabezeichenfolge hat das falsche Format."
In C:\XXX\XXXX\XXXXX\Wreckfest-eventloop-randomizer-main\script\WreckFest_ERS.ps1:64 Zeichen:19
+         $rt_map = Get-Random $($types[$rt].Maps) # pick a random map  ...
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Random], PSInvalidCastException
    + FullyQualifiedErrorId : InvalidCastFromStringToInteger,Microsoft.PowerShell.Commands.GetRandomCommand

Thank you

**Comment by Hedrauta** [comment]
already got that... fixed it with https://github.com/Hedrauta/Wreckfest-eventloop-randomizer/commit/fcb07fb71c113a605c0386b9a53850468a611d3e
Something about the -Maximum in the Get-Random had changed.... it should work fine now ;) sorry that slow respond :D had some issues with my PC ^.^
