### ISSUE TITLE
Derby Deathmatch und Team Derby export as "none"

### ISSUE THREAD

**Issue by phiniksplays** [Hedrauta/Wreckfest-eventloop-randomizer#5]
Yeah theres a problem with the derby options they are exported as "none"
![notepad_2021-10-20_17-56-06](https://user-images.githubusercontent.com/80781063/138128371-18fd374d-1e22-407a-96e3-305eab862f0d.png)

**Comment by Hedrauta** [comment]
🤔

**Comment by Hedrauta** [comment]
Ye... installing GitHub on my phone worked awesome.... like: it didn't.... watching into the bug....

**Comment by phiniksplays** [comment]
> 
> 
> Ye... installing GitHub on my phone worked awesome.... like: it didn't.... watching into the bug....

no problem looking forward for the next update.... if you decide to update it hehe :P

**Comment by Hedrauta** [comment]
Currently working on another project... But will do asap

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Hedrauta** [comment]
dunno.... now it will set it right.... took me a bit to find the brain-lag 🤣 

Will also look the next days into new maps.... may have passed a few ones...
