### ISSUE TITLE
Cant run the powershelf script

### ISSUE THREAD

**Issue by phiniksplays** [Hedrauta/Wreckfest-eventloop-randomizer#6]
Hey, it's me agian i cant run your newewst version. I dunno why and i also did the powershelf administrator move. But when i run you command there "set-executionpolicy remotesigned" he put out valous i dont understand. And give me a list with . Yes. no . Yes all. cancel... wait i give you a link to the scene because i did a livestream there.... short: i wasnt able to get it run...

https://www.twitch.tv/videos/1221076785?t=00h26m42s

**Comment by Hedrauta** [comment]
😆  jo... sorry.... das kam **mal wieder** keine Benachrichtigung... und ich was etwas hart in Javascript vertieft 😉 
Langsam geht mir diese "nicht benachrichtigen" schon etwas hart auf den Senkel 😑 

Also... `Set-ExecutionPolicy RemoteSigned` ist dafür da, um die Ausführung von "signierten" Skripten zu erlauben.

Nach der Ausführung wird **keine** Bestätigung ausgegeben... 

Um dann auch noch das Skript starten zu können muss das Zertifikat installiert werden... ( da nur das Zertifikat die Signatur enthält, damit Windows sich nicht gleich ins Höschen macht 😉 )

Alternativ kann man auch etwas "gefährlicher" spielen und den Spaß mit dem Zertifikat komplett ignorieren...
der Befehl dafür ist `Set-ExecutionPolicy Unrestricted` ... 
Danach ist aber das Ausführen von "allen" Skripten erlaubt, wovon meist abgeraten wird... 

Möglichkeit: erst mit `Unrestricted` das Ausführen erlauben, und nach dem "randomisieren" einfach mit `Default` wieder auf Microsofts Paranoia-Einstellung zurückschalten lassen... 

Ich lasse mir die Tage mal eine Alternative einfallen, da diese  ♥♥♥♥♥ Ausführ-Paranoia von Microdoof schon etwas hart auf den Senkel geht 😉 
Gruß: H3draut3r

**Comment by Hedrauta** [comment]
Die neue Anleitung (einsehbar auf der Haupt-Seite) sollte nun etwas detaillierter sein 😉
